# Generated by Django 3.2.5 on 2021-07-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.CharField(max_length=100)),
                ("project_name", models.CharField(max_length=256)),
                ("amount", models.FloatField(default=0)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
