# Generated by Django 3.2.5 on 2021-07-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
