# Generated by Django 3.2.5 on 2021-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
